name: Selenium Tests

on:
  push:
    branches: [ "ci-cd-tests", "feature-pdf-email", "master" ]
  pull_request:
    branches: [ "ci-cd-tests" ]
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'  # 07:00 Chile (CLST UTC-3)

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Instalar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'

    # MOVIDO AQUÍ: Primero preparamos el sistema con los motores de imagen/PDF
    - name: Instalar dependencias del sistema (Poppler y wkhtmltopdf)
      run: |
        sudo apt-get update
        sudo apt-get install -y wkhtmltopdf poppler-utils

    - name: Instalar dependencias de Python
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Instalar Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable

    - name: Ejecutar tests
      env:
        CI: "true"
        TZ: "America/Santiago"
        PORTAL_USER: ${{ secrets.PORTAL_USER }}
        PORTAL_PASS: ${{ secrets.PORTAL_PASS }}
      run: pytest tests -s

    - name: Generar PDF Consolidado
      if: always()
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: python utils/pdf_merger.py

    - name: Comprimir en ZIP
      if: always()
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: python utils/zipper.py

    - name: Subir Reporte Final (ZIP)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Paquete-Auditoria-Final
        path: "*.zip"

    - name: Subir evidencias sueltas (Opcional)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: evidencias-tecnicas
        path: |
          reports/
          screenshots/

    - name: Enviar Correo con Reporte
      if: always()
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        PYTHONPATH: ${{ github.workspace }}
      run: python utils/enviar_correo.py